# Generated by Django 2.0.3 on 2020-04-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20200408_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('O', 'Out for Delivery'), ('C', 'Completed')], max_length=1),
        ),
    ]
