# Generated by Django 2.0.3 on 2020-04-16 22:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20200408_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularpizza',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
