# Generated by Django 2.0.3 on 2020-04-16 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20200416_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularpizza',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('L', 'Large')], max_length=1),
        ),
    ]
