# Generated by Django 2.0.3 on 2020-04-16 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20200416_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('L', 'Large')], default='—', max_length=1),
        ),
        migrations.AlterField(
            model_name='dinnerplatter',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('L', 'Large')], max_length=1),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('L', 'Large')], default='—', max_length=1),
        ),
        migrations.AlterField(
            model_name='sicilianpizza',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('L', 'Large')], max_length=1),
        ),
        migrations.AlterField(
            model_name='sub',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('L', 'Large')], max_length=1),
        ),
    ]
