# Generated by Django 2.0.3 on 2020-04-16 23:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20200416_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularpizza',
            name='num_toppings',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='sicilianpizza',
            name='num_toppings',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
