# Generated by Django 2.0.3 on 2020-04-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20200416_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('O', 'Out for Delivery'), ('C', 'Completed'), ('R', 'Ready for Pickup')], max_length=1),
        ),
    ]
